### ISSUE TITLE
Authors name in path causes error in tutorial code

### ISSUE THREAD

**Issue by AceMcAwesome77** [aehrc/cxrmate#2]
Hi, I tried to download this and run the first example here on github: 

dlhpcstarter -t cxrmate_hf -c config/test_huggingface/longitudinal_gen_prompt_cxr-bert.yaml --stages_module tools.stages --test

But I get an error right away that suggests the code authors name is still hardcoded in a path somewhere?  Does that need to be fixed?  What is that paths.yaml file its referring to?  Thanks!

(base) C:\Users\myusername\Desktop\cxrmate>dlhpcstarter -t cxrmate_hf -c config/test_huggingface/longitudinal_gen_prompt_cxr-bert.yaml --stages_module tools.stages --test
Traceback (most recent call last):
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\robert.harris\AppData\Local\anaconda3\Scripts\dlhpcstarter.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\dlhpcstarter\__main__.py", line 49, in main
    load_config_and_update_args(args=args, print_args=True)
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\dlhpcstarter\utils.py", line 79, in load_config_and_update_args
    config = compose(config_name=args.config_name)
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\compose.py", line 38, in compose
    cfg = gh.hydra.compose_config(
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\config_loader_impl.py", line 253, in _load_configuration_impl
    defaults_list = create_defaults_list(
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\defaults_list.py", line 745, in create_defaults_list
    defaults, tree = _create_defaults_list(
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\defaults_list.py", line 715, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\defaults_list.py", line 356, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\defaults_list.py", line 457, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\defaults_list.py", line 280, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\defaults_list.py", line 573, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\defaults_list.py", line 520, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\defaults_list.py", line 573, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\defaults_list.py", line 520, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\defaults_list.py", line 488, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "C:\Users\robert.harris\AppData\Local\anaconda3\lib\site-packages\hydra\_internal\defaults_list.py", line 799, in config_not_found_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: In 'single_tf': Could not load '/home/anicolson/config/paths.yaml'.

**Comment by anicolson** [comment]
Hi AceMcAwesome77, this should be fixed now.
